DELIMITER $$

CREATE FUNCTION TOTAL_SALES(total INT)
RETURNS INT
DETERMINISTIC
BEGIN
    RETURN (total * 400);
END $$

DELIMITER ;

-- Example query using the function
SELECT EVENT_NAME, TOTAL_SALES(TABLE4.TOTAL_ATTENDEES) FROM TABLE4;
