CREATE OR REPLACE VIEW TABLE1 AS
SELECT 
    BILLS.BILL_ID, 
    SUPPLIER.SUPPLIER_ID, 
    SUPPLIER.SUPPLIER_NAME, 
    BILLS.AMOUNT, 
    BILLS.PAYMENT_STATUS
FROM BILLS
LEFT JOIN SUPPLIER ON BILLS.SUPPLIER_ID = SUPPLIER.SUPPLIER_ID;

CREATE OR REPLACE VIEW TABLE2 AS
SELECT 
    BILLS.BILL_ID, 
    HOSTS.HOST_ID, 
    HOSTS.HOST_NAME, 
    BILLS.AMOUNT, 
    BILLS.PAYMENT_STATUS
FROM BILLS
LEFT JOIN HOSTS ON BILLS.HOST_ID = HOSTS.HOST_ID;

CREATE OR REPLACE VIEW TABLE3 AS
SELECT 
    BILLS.BILL_ID, 
    EVENTS.EVENT_ID, 
    EVENTS.EVENT_NAME, 
    BILLS.AMOUNT, 
    BILLS.PAYMENT_STATUS
FROM BILLS
LEFT JOIN EVENTS ON BILLS.EVENT_ID = EVENTS.EVENT_ID;

CREATE OR REPLACE VIEW TABLE4 AS
SELECT 
    EVENTS.EVENT_NAME, 
    COUNT(ATTENDED_BY.USER_ID) AS TOTAL_ATTENDEES
FROM ATTENDED_BY
LEFT JOIN EVENTS ON ATTENDED_BY.EVENT_ID = EVENTS.EVENT_ID
GROUP BY ATTENDED_BY.EVENT_ID;
